# Based on https://dev.to/github/how-to-build-google-like-forms-with-github-3ig2
name: Article Submission
description: Contribute an article to the Code blog
title: "[Title]: "
labels: []
assignees:
  - thombruce
body:
  - type: markdown
    attributes:
      value: |
        Use this form to submit an article to _Code_ for consideration to be included on the blog.

  - type: input
    id: title
    attributes:
      label: Title
      description: What is the title of your article?
      placeholder: e.g. Writing Kickass Articles
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author Name
      description: What is your name?
      placeholder: e.g. Thom Bruce
    validations:
      required: true

  - type: textarea
    id: article
    attributes:
      label: Article Body
      description: Please provide your article in Markdown format.
      render: markdown
    validations:
      required: true
